### PR TITLE
Update to 0.3.5

### LINKED ISSUE #11: Update spreedme version?
@oparoz 0.3.5 is released, does the snap handle this automatically or do we need to change version number?

https://github.com/strukturag/nextcloud-spreedme/releases

### PR DESCRIPTION
**Pull request by enoch85**
@oparoz I have no clue really. But like this?

Fixes #11

### CODE REVIEW

**Comment by oparoz** [comment]
Yeah, should work if you've used the name of the branches on Github :)

**Comment by oparoz** [comment]
OK, the problem now is that someone needs to compile and test the snap...

So maybe I need to setup a develop branch which can automatically build snaps for people to test...

**Comment by enoch85** [comment]
https://github.com/strukturag/nextcloud-spreedme/tree/release-0.3

So it should be 0.3 not 0.30?

**Comment by oparoz** [comment]
Correct

**Comment by enoch85** [comment]
Ok then, already on the latest branch, no need to upgrade. :]

**Comment by oparoz** [comment]
I'll need to regenerate snaps then

**Comment by oparoz** [comment]
Hold on... current release is 0.29 branch, so this PR would still update the snap.

**Comment by enoch85** [comment]
https://github.com/strukturag/spreed-webrtc/branches Same branch as current. Feel free to close.

Also, https://github.com/strukturag/nextcloud-spreedme/branches

**Pull request closed without merging**
