### PR TITLE
Update Readme to latest SpreedME version

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by enoch85** [comment]
cc @oparoz

**Comment by oparoz** [comment]
Please rebase to 0.3.6 and I'll merge this

**Comment by enoch85** [comment]
Don't know how :S

**Comment by oparoz** [comment]
I mean the readme. There is also a typo: Nextloucd VM

**Comment by enoch85** [comment]
Done

**Comment by oparoz** [comment]
Thank you :)

**Pull request merged**
